[workspace]
resolver = "2"
members = [
  "nethsm",
  "nethsm-cli",
  "nethsm-config",
]

[workspace.dependencies]
rstest = "0.23.0"
testdir = "0.9.1"
testresult = "0.4.1"
thiserror = "1.0.64"

[workspace.package]
authors = [
  "David Runge <dvzrv@archlinux.org>",
  "Wiktor Kwapisiewicz <wiktor@archlinux.org>",
]
edition = "2021"
homepage = "https://gitlab.archlinux.org/archlinux/signstar"
license = "Apache-2.0 OR MIT"
repository = "https://gitlab.archlinux.org/archlinux/signstar"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
