[advisories]
version = 2
yanked = "deny"
ignore = [
  "RUSTSEC-2023-0071",  # side-channel attacks are not relevant for our use-case (only used in tests)
  "RUSTSEC-2023-0050",  # nethsm-sdk-rs uses unmaintained multipart until something else becomes available: https://github.com/Nitrokey/nethsm-sdk-rs/issues/29
]

[bans]
deny = [
]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "LicenseRef-ring",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
