# NOTE: This project does not attribute contributors individually. Instead refer to `git log --format="%an <%aE>" | sort -u` for a list of individual contributors.
SPDX-PackageDownloadLocation = "https://gitlab.archlinux.org/archlinux/signstar"
SPDX-PackageName = "signstar"
SPDX-PackageSupplier = "Arch Linux"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "Signstar Contributors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
path = ["**.rs"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Signstar Contributors"
SPDX-License-Identifier = "CC0-1.0"
path = [
    "**.snap",
    "**.toml",
    "**.yaml",
    "**justfile",
    "*.json",
    ".cargo/runner.sh",
    ".codespellrc",
    ".gitignore",
    ".gitlab-ci.yml",
    ".gitlab/CODEOWNERS",
    ".lycheeignore",
    ".shellcheckrc",
    "Cargo.lock",
    "lychee.toml",
    "resources/docs/src/api-docs/dependency_graph.png",
    "signstar-crypto/tests/fixtures/*.asc",
    "signstar-request-signature/tests/*.json",
    "signstar-request-signature/tests/sshd/*",
    "signstar-yubihsm2/tests/backup/*.yhw",
    "signstar-yubihsm2/tests/backup/wrap-key",
    "signstar-yubihsm2/tests/scenarios/**.json",
    "signstar-yubihsm2/tests/scenarios/data/opaque-data",
    "signstar-yubihsm2/tests/scenarios/keys/*",
]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Signstar Contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path = ["**.excalidraw", "**.md", "**.png", "**.svg"]
precedence = "aggregate"
