[formatting]
indent_string = "    "
reorder_arrays = true
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["package"]

[rule.formatting]
reorder_keys = false

[[rule]]
# files that are compared for bit-for-bit equivalence but are generated
# using confy do not have keys sorted. Disable checks for them now
# Alternatively they could be compared in a TOML-semantic aware fashion.
include = [
    "nethsm-config/tests/fixtures/roundtrip-config/basic-config.toml",
    "signstar-config/tests/fixtures/admin-creds-simple.toml",
]

[rule.formatting]
reorder_keys = false
