[package]
authors.workspace = true
description = "A high-level library to interact with the API of a Nitrokey NetHSM"
edition.workspace = true
homepage.workspace = true
keywords = ["encryption", "hsm", "nethsm", "signing"]
license.workspace = true
name = "nethsm"
repository.workspace = true
version = "0.6.0"

[package.metadata.cargo-machete]
ignored = ["md-5"]

[dependencies]
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
chrono = { workspace = true, features = ["alloc"] }
ed25519-dalek = { workspace = true, features = ["pkcs8", "pem"] }
email_address = "0.2.8"
fqdn = { version = "0.4.2", features = ["strict-rfc"] }
hex = { version = "0.4.3", features = ["serde"] }
log = "0.4.22"
md-5 = "0.10.6"
nethsm-sdk-rs = "1.1.1"
p224 = { version = "0.13.2", features = ["pem", "pkcs8"] }
p256 = { version = "0.13.2", features = ["pem", "pkcs8"] }
p384 = { version = "0.13.0", features = ["pem", "pkcs8"] }
p521 = { version = "0.13.3", features = ["pem", "pkcs8"] }
pgp = "0.14"
picky-asn1-der = "0.5.0"
picky-asn1-x509 = "0.13.0"
rand.workspace = true
rsa = { workspace = true, features = ["pem"] }
rustls = { version = "0.23.14", default-features = false, features = ["ring"] }
rustls-native-certs = "0.8.0"
secrecy = { version = "0.10.2", features = ["serde"] }
serde.workspace = true
serde_json = "1.0.128"
sha1 = "0.10.6"
sha2 = { version = "0.10.8", features = ["oid"] }
strum.workspace = true
thiserror.workspace = true
ureq = { version = "2.10.1", features = ["json"] }
url = { version = "2.5.2", features = ["serde"] }

[dev-dependencies]
ed25519-dalek = { workspace = true, features = ["pkcs8", "pem", "rand_core"] }
rsa = { workspace = true, features = ["getrandom", "sha2", "pem"] }
rstest.workspace = true
rustainers = { version = "0.13.1" }
testdir.workspace = true
testresult.workspace = true
tokio = { version = "1.40.0", features = ["macros"] }
uuid = { version = "1.10.0", features = ["v7"] }

