admin_secret_handling = "shamirs-secret-sharing"
iteration = 1
non_admin_secret_handling = "systemd-creds"

[[connections]]
nethsm = { tls_security = "Unsafe", url = "https://localhost:8443/api/v1/" }

[[users]]
nethsm_only_admin = "admin"

[[users]]

# NOTE: the authorized_keys are dummy entries for now
[users.system_only_share_download]
ssh_authorized_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOh96uFTnvX6P1ebbLxXFvy6sK7qFqlMHDOuJ0TmuXQQ user@host"
system_user = "ssh-share-down"

[[users]]

# NOTE: the authorized_keys are dummy entries for now
[users.system_only_share_upload]
ssh_authorized_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOh96uFTnvX6P1ebbLxXFvy6sK7qFqlMHDOuJ0TmuXQQ user@host"
system_user = "ssh-share-up"
