[package]
authors = ["David Runge <dvzrv@archlinux.org>"]
description = "A CLI for the Nitrokey NetHSM"
edition = "2021"
keywords = ["encryption", "hsm", "nethsm", "signing", "cli"]
license = "Apache-2.0 OR MIT"
name = "nethsm-cli"
repository = "https://gitlab.archlinux.org/archlinux/signstar"
version = "0.2.2"

[dependencies]
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive", "env"] }
nethsm = { path = "../nethsm", version = "0.6.0" }
nethsm-config = { path = "../nethsm-config", version = "0.1.0" }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.58"

[[bin]]
name = "nethsm"
path = "src/main.rs"

[dev-dependencies]
rand = "0.8.5"
rstest = "0.22.0"
testdir = "0.9.1"
testresult = "0.4.0"
