FROM archlinux

WORKDIR /test

RUN pacman-key --init && pacman -Sy --needed --noconfirm archlinux-keyring && cat .env && source /test/.env && pacman -Syu --needed --noconfirm $PACMAN_PACKAGES && just install-rust-dev-tools
